// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package emodl

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson515ca9ccDecodeGithubComJdavasligilEmodl(in *jlexer.Lexer, out *BTTVEmoteSlice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(BTTVEmoteSlice, 0, 0)
			} else {
				*out = BTTVEmoteSlice{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 BTTVEmote
			easyjson515ca9ccDecodeGithubComJdavasligilEmodl1(in, &v1)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson515ca9ccEncodeGithubComJdavasligilEmodl(out *jwriter.Writer, in BTTVEmoteSlice) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			easyjson515ca9ccEncodeGithubComJdavasligilEmodl1(out, v3)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v BTTVEmoteSlice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson515ca9ccEncodeGithubComJdavasligilEmodl(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BTTVEmoteSlice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson515ca9ccEncodeGithubComJdavasligilEmodl(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BTTVEmoteSlice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson515ca9ccDecodeGithubComJdavasligilEmodl(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BTTVEmoteSlice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson515ca9ccDecodeGithubComJdavasligilEmodl(l, v)
}
func easyjson515ca9ccDecodeGithubComJdavasligilEmodl1(in *jlexer.Lexer, out *BTTVEmote) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "code":
			out.Name = string(in.String())
		case "imageType":
			out.ImageType = string(in.StringIntern())
		case "animated":
			out.Animated = bool(in.Bool())
		case "userID":
			out.UserID = string(in.StringIntern())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson515ca9ccEncodeGithubComJdavasligilEmodl1(out *jwriter.Writer, in BTTVEmote) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"imageType\":"
		out.RawString(prefix)
		out.String(string(in.ImageType))
	}
	{
		const prefix string = ",\"animated\":"
		out.RawString(prefix)
		out.Bool(bool(in.Animated))
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	out.RawByte('}')
}
